language: ruby
addons:
  code_climate:
    repo_token: 6f07a33d1bf4060910c8b97cb9bf97230bbf1fad75765fef98f3cca9f29cd6b0
before_install:
  - gem install bundler
install:
  - bundle install --without local
rvm:
  - 2.5.0
  - 2.4.3
  - 2.4.2
  - 2.4.1
  - 2.4.0
  - 2.3.6
  - 2.3.5
  - 2.3.4
  - 2.3.3
  - 2.3.2
  - 2.3.1
  - 2.3.0
  - 2.2.9
  - 2.2.8
  - 2.2.7
  - 2.2.6
  - 2.2.5
  - 2.2.4
  - 2.2.3
  - 2.2.2
  - 2.2.1
  - 2.2.0
